version: "3"
services:
  blockend:
    build:
      context: .
      dockerfile: Dockerfile
    image: blockend
    container_name: blockend
    restart: unless-stopped
    working_dir: /code
    env_file: .env
    ports:
      - 3001:3001
    volumes:
      - ./:/code
    networks:
      - blockheads
    depends_on:
      - mongo
  indexer:
    build:
      context: .
      dockerfile: DockerfileIndexer
    image: blockend-indexer
    container_name: blockend-indexer
    restart: unless-stopped
    working_dir: /code
    env_file: .env
    ports:
      - 3002:3002
    volumes:
      - ./:/code
    networks:
      - blockheads
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  
  # nginx:
  #   image: nginx:1.17-alpine
  #   container_name: roh-nginx
  #   restart: unless-stopped
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   networks:
  #     - blockheads

networks:
  blockheads:
    driver: bridge
